name: twirp_dart_core
description: Core library for using Twirp + Dart
version: 1.0.0+1
homepage: https://github.com/apptreesoftware/twirp_dart_core
author: Matthew Smith<matthew.smith@apptreesoftware.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  http: ^0.12.1
  requester:
    git:
      url: https://github.com/ragnor-rs/requester.git
      ref: 54ffd61703051ab1800371371a85ef80f6768251

dev_dependencies:
  test: ^1.0.0
